from fpdf import FPDF
import pandas as pd
from typing import Dict, Any, List

class SalesReportPDF(FPDF):
    def header(self):
        # Dark top bar header
        self.set_fill_color(15, 23, 42) # Slate dark
        self.rect(0, 0, 210, 24, "F")
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(232, 184, 75) # Gold accent
        self.set_xy(14, 6)
        self.cell(0, 10, "TALLY  -  RETAIL SALES REPORT", ln=1, align="L")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "", 9)
        self.set_xy(14, 15)
        self.cell(0, 5, "Automated Sales Analytics & Revenue Insights Report", ln=1, align="L")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Tally Sales Data Analyzer", align="C")

def sanitize_pdf_text(text: str) -> str:
    if not text:
        return ""
    return str(text).replace("–", "-").replace("—", "-").replace("▲", "+").replace("▼", "-")

def generate_pdf_report(
    date_range_str: str,
    kpis: List[Dict[str, Any]],
    top_products: List[Dict[str, Any]],
    monthly_trend: List[Dict[str, Any]],
    prediction: Dict[str, Any]
) -> bytes:
    pdf = SalesReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Section 1: Overview & Date Range
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, sanitize_pdf_text(f"Report Period: {date_range_str}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Section 2: Key Performance Indicators (KPI Summary Table)
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "1. Executive Summary & KPIs", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table Header
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(70, 7, " Metric Label", border=1, fill=True)
    pdf.cell(60, 7, " Value", border=1, fill=True)
    pdf.cell(50, 7, " PoP Delta", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    # Table Body
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "", 9.5)
    for i, kpi in enumerate(kpis):
        bg = (248, 250, 252) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.cell(70, 7, sanitize_pdf_text(f" {kpi.get('label', '')}"), border=1, fill=True)
        pdf.cell(60, 7, sanitize_pdf_text(f" {kpi.get('value', '')}"), border=1, fill=True)
        
        delta_str = sanitize_pdf_text(kpi.get('delta', ''))
        pdf.cell(50, 7, f" {delta_str}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)

    # Section 3: Next-Month Revenue Forecast
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "2. Next-Month Predictive Forecast", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_fill_color(254, 243, 199) # Gold tint
    pdf.rect(14, pdf.get_y(), 180, 20, "F")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(146, 64, 14)
    pdf.set_xy(18, pdf.get_y() + 3)
    target_info = sanitize_pdf_text(f"Target Period: {prediction.get('nextMonth', 'Next Month')} | Predicted Revenue: {prediction.get('value', 'N/A')}")
    pdf.cell(0, 5, target_info, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_xy(18, pdf.get_y() + 1)
    range_info = sanitize_pdf_text(f"Expected Range: {prediction.get('range', '')}  |  Confidence Score: {prediction.get('confidence', '')}  |  R2: {prediction.get('r2', '')}")
    pdf.cell(0, 5, range_info, new_x="LMARGIN", new_y="NEXT")
    pdf.set_y(pdf.get_y() + 6)
    pdf.ln(6)

    # Section 4: Top 5 Best-Selling Products Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "3. Top 5 Best-Selling Products", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(15, 7, " Rank", border=1, fill=True)
    pdf.cell(75, 7, " Product Name", border=1, fill=True)
    pdf.cell(30, 7, " Units Sold", border=1, fill=True)
    pdf.cell(35, 7, " Total Revenue", border=1, fill=True)
    pdf.cell(25, 7, " Trend %", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "", 9)
    for i, prod in enumerate(top_products):
        bg = (248, 250, 252) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.cell(15, 7, f" #{prod.get('rank', i+1)}", border=1, fill=True)
        pdf.cell(75, 7, sanitize_pdf_text(f" {prod.get('name', '')[:35]}"), border=1, fill=True)
        pdf.cell(30, 7, f" {prod.get('units', 0):,}", border=1, fill=True)
        pdf.cell(35, 7, f" ${prod.get('revenue', 0):,.2f}", border=1, fill=True)
        
        trend = prod.get('trend', 0.0)
        trend_str = f"+{trend:.1f}%" if trend >= 0 else f"{trend:.1f}%"
        pdf.cell(25, 7, f" {trend_str}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)

    # Section 5: Monthly Revenue Breakdown Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "4. Monthly Sales Performance Breakdown", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(90, 7, " Month", border=1, fill=True)
    pdf.cell(90, 7, " Revenue ($)", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "", 9)
    for i, item in enumerate(monthly_trend):
        bg = (248, 250, 252) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.cell(90, 6.5, sanitize_pdf_text(f" {item.get('month', '')}"), border=1, fill=True)
        pdf.cell(90, 6.5, f" ${item.get('revenue', 0.0):,.2f}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    # Output bytes
    return bytes(pdf.output())
